// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v4.25.3
// source: api/smsff.proto

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSmsFFSendSms = "/dnzzzsmsff.api.SmsFF/SendSms"

type SmsFFHTTPServer interface {
	SendSms(context.Context, *SendSmsReq) (*SendSmsResp, error)
}

func RegisterSmsFFHTTPServer(s *http.Server, srv SmsFFHTTPServer) {
	r := s.Route("/")
	r.POST("/sendsms", _SmsFF_SendSms0_HTTP_Handler(srv))
}

func _SmsFF_SendSms0_HTTP_Handler(srv SmsFFHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendSmsReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSmsFFSendSms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendSms(ctx, req.(*SendSmsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendSmsResp)
		return ctx.Result(200, reply)
	}
}

type SmsFFHTTPClient interface {
	SendSms(ctx context.Context, req *SendSmsReq, opts ...http.CallOption) (rsp *SendSmsResp, err error)
}

type SmsFFHTTPClientImpl struct {
	cc *http.Client
}

func NewSmsFFHTTPClient(client *http.Client) SmsFFHTTPClient {
	return &SmsFFHTTPClientImpl{client}
}

func (c *SmsFFHTTPClientImpl) SendSms(ctx context.Context, in *SendSmsReq, opts ...http.CallOption) (*SendSmsResp, error) {
	var out SendSmsResp
	pattern := "/sendsms"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSmsFFSendSms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
